spring.application.name=ecommerce
spring.profiles.active=dev
# spring.datasource.url=jdbc:postgresql://localhost:5432/shop
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.datasource.testWhileIdle=true
# spring.datasource.validationQuery=SELECT 1
# ===============================
# = JPA / HIBERNATE
# ===============================
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# MONGODB
spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
# Mongo configuration settings


# REDIS
spring.data.redis.host=redis
spring.data.redis.port=6379

# OLLAMA
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.chat.options.temperature=0.7

# GEMINI AI 
spring.ai.vertex.ai.gemini.projectId=PruebaIAGemini
spring.ai.vertex.ai.gemini.location=us-east4
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash-lite
spring.ai.vertex.ai.gemini.chat.options.temperature=0.5

